<!DOCTYPE html>
<html>
<head>
  <title>task5</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
  
    

<!-- nav bar -->

<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a class="navbar-brand ml-5" href="#" style="color: white;">Fresh</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto mr-5">
      <li class="nav-item active">
        <a class="nav-link" href="#" style="color: white;">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color: white;">Feature</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color: white;">Portfolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color: white;">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color: white;">Contact us</a>
      </li>
    </ul>
  </div>
</nav>

      
  

  <!-- header2 -->

  <div class="container-fluid" style="background-color: #13a89e; padding-bottom: 30px;">
    <div class="row">
      <div class="col-lg-12">
        <h2 style="color: white;" class="text-center">BIG BOLD CALL TO ACTION!</h2>
        <p style="color: white; padding:0 60px 0 60px;" class="text-justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <div class="text-center">
        <a href="#" type="button" class="btn btn-light" >Clik Me</a>
<a href="#" type="button" class="btn bg-dark text-white">Purchase now</a></div>
      </div>
    </div>
  </div>

  <!-- main -->
<main>
  <div class="container">
    <h4 class="text-center pt-5 font-weight-bold">WHAT TO DO</h4><br>
    <div class="row">
      
          
          


          <!-- card -->
       <div class="col-lg-3">
          <div class="card card-img">
            <img src="Bootstrap_Task\task5\star.jpg" class="img-fluid card-img-top pt-3 pb-3" style="width:120px;margin-left: 60px; height: 143px;"> 
            <h5 class="text-center">Star Power</h5>
      <p class="text-center pl-3">sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <a href="#" class="text-center">click here</a>
          </div>
        </div>


        <div class="col-lg-3">
          <div class="card">
            <img src="Bootstrap_Task\task5\microphone.jpg" class="img-fluid card-img-top p-3" style="width:150px;margin-left: 60px;"> 
      <h5 class="text-center">Star Power</h5>
      <p class="text-center pl-3">sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <a href="#" class="text-center">click here</a>
          </div>
        </div>




        <div class="col-lg-3">
          <div class="card">
            <img src="Bootstrap_Task\task5\people.webp" class="img-fluid card-img-top p-3" style="width:150px;margin-left: 60px;height: 144px;"> 
      <h5 class="text-center">Star Power</h5>
      <p class="text-center pl-3">sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <a href="#" class="text-center">click here</a>
          </div>
        </div>





<div class="col-lg-3">
          <div class="card">
            <img src="Bootstrap_Task\task5\networks.jpg" class="img-fluid card-img-top p-3" style="width:150px;margin-left: 60px; height: 145px;"> 
     <h5 class="text-center">Star Power</h5>
      <p class="text-center pl-3">sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <a href="#" class="text-center">click here</a>
          </div>
        </div>

            

      </div>
    </div>
  </div>


            <div class="container">
    <h4 class="text-center pt-5 font-weight-bold">LATEST PROJECT </h4><br>

     <div class="row">
      
          
          


          <!-- card2 -->


       <div class="col-lg-4">
          <div class="card card-img">
            <img src="Bootstrap_Task\task1\roses.jpg" class="img-fluid card-img-top"> 
            
          </div>
        </div>


        <div class="col-lg-4">
          <div class="card card-img">
            <img src="Bootstrap_Task\task1\roses.jpg" class="img-fluid card-img-top"> 
            
          </div>
        </div>



       <div class="col-lg-4 mb-4">
          <div class="card card-img">
            <img src="Bootstrap_Task\task1\roses.jpg" class="img-fluid card-img-top"> 
            
          </div>
        </div>


      <div class="col-lg-4">
          <div class="card card-img">
            <img src="Bootstrap_Task\task1\roses.jpg" class="img-fluid card-img-top"> 
            
          </div>
        </div>

        <div class="col-lg-4">
          <div class="card card-img">
            <img src="Bootstrap_Task\task1\roses.jpg" class="img-fluid card-img-top"> 
            
          </div>
        </div>


        <div class="col-lg-4">
          <div class="card card-img">
            <img src="Bootstrap_Task\task1\roses.jpg" class="img-fluid card-img-top"> 
            
          </div>
        </div>

            

      </div>
    </div>
  </div><br>

        <h4 class="text-center font-weight-bold">WE WOULD LOVE TO HEAR FROM YOU! &nbsp; <button> Get in touch>></button></h4><br>


</main>

<footer>
  <div class="container-fluid bg-dark">
    <div class="row">
      <div class="col-lg-3">
        <div>
          <ul style="color: gray;">Links              
              <li>Home</li>
              <li>About</li>
              <li>Contact us</li>
              <li>services</li>
          </ul>
        </div></div>


        <div class="col-lg-3">
        <div>
          <ul  style="color: gray;">              
              <li class="pt-4">Home</li>
              <li>About</li>
              <li>Contact us</li>
              <li>services</li>
          </ul>
        </div></div>


          <div class="col-lg-3">
          <div class="text-center">
            <h3 style="color: gray;">Connect With Us</h3>
            <p style="color: gray;">loreum ipsum Lorem ipsum dolor sit amet, consectetur</p>

          </div></div>



          <div class="col-lg-3 pt-4">
          <div class="text-center">
            <h3 style="color: gray;">Subscribe</h3>

            <input type="email" name="" placeholder="Enter your Email ">
            <button type="submit">Submit</button>
          </div></div>
    </div>
  </div>
</footer>


      <!-- Footer -->
<div class="container-fluid bg-light">
  <div class="row">
    <div class="col-lg-12">
      <p class="text-center">Copyright@ your website 2019</p>
    </div>
  </div>
</div>

</body>
</html>